# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.FloatField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
