# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0002_product_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
