# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0004_auto_20171018_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_species',
            new_name='subcategory',
        ),
    ]
