# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0005_auto_20171018_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0, max_length=100),
        ),
    ]
